<?php

return [
	'employee_directory' => [
		'title' => 'Employee Directory Report',
		'generated_on' => 'Generated on',
		'generated_by' => 'Generated by HRMS',
		'filters' => [
			'department' => 'Department',
			'position' => 'Position',
			'status' => 'Status',
		],
		'headers' => [
			'employee_code' => 'Employee Code',
			'full_name' => 'Full Name',
			'department' => 'Department',
			'position' => 'Position',
			'employment_status' => 'Status',
			'hire_date' => 'Hire Date',
			'manager' => 'Manager',
		],
		'footer_total' => 'Total Employees',
	],
];
