<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ __('Attendance Summary Report') }} - {{ $month }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 10px;
            line-height: 1.4;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #c6a44a;
            padding-bottom: 10px;
        }
        .company-name {
            font-size: 16px;
            font-weight: bold;
            color: #2e4029;
            margin-bottom: 5px;
        }
        .report-title {
            font-size: 14px;
            color: #c6a44a;
            margin-bottom: 5px;
        }
        .report-date {
            font-size: 10px;
            color: #666;
        }
        .summary {
            margin-bottom: 20px;
            padding: 10px;
            background-color: #f9f5e6;
            border: 1px solid #c6a44a;
        }
        .summary-item {
            display: inline-block;
            margin-right: 20px;
            margin-bottom: 5px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #2e4029;
            color: white;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .number {
            text-align: right;
            font-weight: bold;
        }
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 8px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 5px;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="company-name">{{ __('Sarie Eldin & Partners Legal Advisors') }}</div>
        <div class="report-title">{{ __('Attendance Summary Report') }}</div>
        <div class="report-date">{{ __('Period') }}: {{ $month }} | {{ __('Generated on') }}: {{ now()->format('F j, Y \a\t g:i A') }}</div>
    </div>

    <div class="summary">
        <strong>{{ __('Summary') }}:</strong><br>
        <div class="summary-item">{{ __('Total Employees') }}: {{ $summary['total_employees'] }}</div>
        <div class="summary-item">{{ __('Total Hours') }}: {{ number_format($summary['total_hours'], 2) }}</div>
        <div class="summary-item">{{ __('Total Overtime') }}: {{ number_format($summary['total_overtime'], 2) }}</div>
        <div class="summary-item">{{ __('Average Hours') }}: {{ number_format($summary['average_hours'], 2) }}</div>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 20%;">{{ __('Employee') }}</th>
                <th style="width: 15%;">{{ __('Department') }}</th>
                <th style="width: 15%;">{{ __('Position') }}</th>
                <th style="width: 12%;">{{ __('Total Hours') }}</th>
                <th style="width: 12%;">{{ __('Overtime Hours') }}</th>
                <th style="width: 8%;">{{ __('Present Days') }}</th>
                <th style="width: 8%;">{{ __('Late Days') }}</th>
                <th style="width: 8%;">{{ __('Absent Days') }}</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data as $attendance)
            <tr>
                <td>{{ $attendance['Employee'] }}</td>
                <td>{{ $attendance['Department'] }}</td>
                <td>{{ $attendance['Position'] }}</td>
                <td class="number">{{ $attendance['Total Hours'] }}</td>
                <td class="number">{{ $attendance['Overtime Hours'] }}</td>
                <td class="number">{{ $attendance['Present Days'] }}</td>
                <td class="number">{{ $attendance['Late Days'] }}</td>
                <td class="number">{{ $attendance['Absent Days'] }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        {{ __('Attendance Summary Report') }} | {{ __('Period') }}: {{ $month }} | {{ __('Total Employees') }}: {{ count($data) }} |
        {{ __('Generated by HRMS') }} | {{ __('Page') }} {PAGENO} {{ __('of') }} {nbpg}
    </div>
</body>
</html>