<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ __('Contract Status Report') }} - {{ now()->format('Y-m-d') }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 10px;
            line-height: 1.4;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #c6a44a;
            padding-bottom: 10px;
        }
        .company-name {
            font-size: 16px;
            font-weight: bold;
            color: #2e4029;
            margin-bottom: 5px;
        }
        .report-title {
            font-size: 14px;
            color: #c6a44a;
            margin-bottom: 5px;
        }
        .report-date {
            font-size: 10px;
            color: #666;
        }
        .summary {
            margin-bottom: 20px;
            padding: 10px;
            background-color: #f9f5e6;
            border: 1px solid #c6a44a;
        }
        .summary-item {
            display: inline-block;
            margin-right: 20px;
            margin-bottom: 5px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #2e4029;
            color: white;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .status-active {
            color: #28a745;
            font-weight: bold;
        }
        .status-expired {
            color: #dc3545;
            font-weight: bold;
        }
        .status-terminated {
            color: #6c757d;
            font-weight: bold;
        }
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 8px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 5px;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="company-name">{{ __('Sarie Eldin & Partners Legal Advisors') }}</div>
        <div class="report-title">{{ __('Contract Status Report') }}</div>
        <div class="report-date">{{ __('Generated on') }}: {{ now()->format('F j, Y \a\t g:i A') }}</div>
    </div>

    <div class="summary">
        <strong>{{ __('Summary') }}:</strong><br>
        <div class="summary-item">{{ __('Total Contracts') }}: {{ $summary['total'] }}</div>
        <div class="summary-item">{{ __('Expiring Soon') }}: {{ $summary['expiring_soon'] }}</div>
        @foreach($summary['by_status'] as $status => $count)
            <div class="summary-item">{{ __(ucfirst($status)) }}: {{ $count }}</div>
        @endforeach
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 20%;">{{ __('Employee') }}</th>
                <th style="width: 15%;">{{ __('Department') }}</th>
                <th style="width: 15%;">{{ __('Contract Type') }}</th>
                <th style="width: 12%;">{{ __('Status') }}</th>
                <th style="width: 12%;">{{ __('Start Date') }}</th>
                <th style="width: 12%;">{{ __('End Date') }}</th>
                <th style="width: 14%;">{{ __('Days Until Expiry') }}</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data as $contract)
            <tr>
                <td>{{ $contract['Employee'] }}</td>
                <td>{{ $contract['Department'] }}</td>
                <td>{{ $contract['Contract Type'] }}</td>
                <td class="status-{{ strtolower($contract['Status']) }}">
                    {{ $contract['Status'] }}
                </td>
                <td>{{ $contract['Start Date'] }}</td>
                <td>{{ $contract['End Date'] }}</td>
                <td>{{ $contract['Days Until Expiry'] }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        {{ __('Contract Status Report') }} | {{ __('Total Contracts') }}: {{ count($data) }} |
        {{ __('Generated by HRMS') }} | {{ __('Page') }} {PAGENO} {{ __('of') }} {nbpg}
    </div>
</body>
</html>