<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ __('Employee Demographics Report') }} - {{ now()->format('Y-m-d') }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 10px;
            line-height: 1.4;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #c6a44a;
            padding-bottom: 10px;
        }
        .company-name {
            font-size: 16px;
            font-weight: bold;
            color: #2e4029;
            margin-bottom: 5px;
        }
        .report-title {
            font-size: 14px;
            color: #c6a44a;
            margin-bottom: 5px;
        }
        .report-date {
            font-size: 10px;
            color: #666;
        }
        .section {
            margin-bottom: 20px;
            page-break-inside: avoid;
        }
        .section-title {
            font-size: 12px;
            font-weight: bold;
            color: #2e4029;
            margin-bottom: 10px;
            border-bottom: 1px solid #c6a44a;
            padding-bottom: 5px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #2e4029;
            color: white;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .chart-item {
            margin-bottom: 5px;
            padding: 3px 0;
        }
        .chart-label {
            display: inline-block;
            width: 150px;
        }
        .chart-value {
            font-weight: bold;
            color: #c6a44a;
        }
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 8px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 5px;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="company-name">{{ __('Sarie Eldin & Partners Legal Advisors') }}</div>
        <div class="report-title">{{ __('Employee Demographics Report') }}</div>
        <div class="report-date">{{ __('Generated on') }}: {{ now()->format('F j, Y \a\t g:i A') }}</div>
    </div>

    <div class="section">
        <div class="section-title">{{ __('By Department') }}</div>
        @foreach($demographics['by_department'] as $department => $count)
        <div class="chart-item">
            <span class="chart-label">{{ $department }}:</span>
            <span class="chart-value">{{ $count }}</span>
        </div>
        @endforeach
    </div>

    <div class="section">
        <div class="section-title">{{ __('By Position') }}</div>
        @foreach($demographics['by_position'] as $position => $count)
        <div class="chart-item">
            <span class="chart-label">{{ $position }}:</span>
            <span class="chart-value">{{ $count }}</span>
        </div>
        @endforeach
    </div>

    <div class="section">
        <div class="section-title">{{ __('By Status') }}</div>
        @foreach($demographics['by_status'] as $status => $count)
        <div class="chart-item">
            <span class="chart-label">{{ __(ucfirst($status)) }}:</span>
            <span class="chart-value">{{ $count }}</span>
        </div>
        @endforeach
    </div>

    <div class="section">
        <div class="section-title">{{ __('By Employment Type') }}</div>
        @foreach($demographics['by_employment_type'] as $type => $count)
        <div class="chart-item">
            <span class="chart-label">{{ $type }}:</span>
            <span class="chart-value">{{ $count }}</span>
        </div>
        @endforeach
    </div>

    <div class="section">
        <div class="section-title">{{ __('By Tenure Group') }}</div>
        @foreach($demographics['by_tenure_group'] as $tenureGroup => $count)
        <div class="chart-item">
            <span class="chart-label">{{ $tenureGroup }}:</span>
            <span class="chart-value">{{ $count }}</span>
        </div>
        @endforeach
    </div>

    <div class="section">
        <div class="section-title">{{ __('By Hire Year') }}</div>
        @foreach($demographics['by_hire_year'] as $year => $count)
        <div class="chart-item">
            <span class="chart-label">{{ $year }}:</span>
            <span class="chart-value">{{ $count }}</span>
        </div>
        @endforeach
    </div>

    <div class="footer">
        {{ __('Employee Demographics Report') }} |
        {{ __('Generated by HRMS') }} | {{ __('Page') }} {PAGENO} {{ __('of') }} {nbpg}
    </div>
</body>
</html>