<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ __('Document Inventory Report') }} - {{ now()->format('Y-m-d') }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 10px;
            line-height: 1.4;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #c6a44a;
            padding-bottom: 10px;
        }
        .company-name {
            font-size: 16px;
            font-weight: bold;
            color: #2e4029;
            margin-bottom: 5px;
        }
        .report-title {
            font-size: 14px;
            color: #c6a44a;
            margin-bottom: 5px;
        }
        .report-date {
            font-size: 10px;
            color: #666;
        }
        .summary {
            margin-bottom: 20px;
            padding: 10px;
            background-color: #f9f5e6;
            border: 1px solid #c6a44a;
        }
        .summary-item {
            display: inline-block;
            margin-right: 20px;
            margin-bottom: 5px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 6px;
            text-align: left;
            font-size: 9px;
        }
        th {
            background-color: #2e4029;
            color: white;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .status-valid {
            color: #28a745;
            font-weight: bold;
        }
        .status-expiring-soon {
            color: #ffc107;
            font-weight: bold;
        }
        .status-expired {
            color: #dc3545;
            font-weight: bold;
        }
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 8px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 5px;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="company-name">{{ __('Sarie Eldin & Partners Legal Advisors') }}</div>
        <div class="report-title">{{ __('Document Inventory Report') }}</div>
        <div class="report-date">{{ __('Generated on') }}: {{ now()->format('F j, Y \a\t g:i A') }}</div>
    </div>

    <div class="summary">
        <strong>{{ __('Summary') }}:</strong><br>
        <div class="summary-item">{{ __('Total Documents') }}: {{ $summary['total'] }}</div>
        <div class="summary-item">{{ __('Expiring Soon') }}: {{ $summary['expiring_soon'] }}</div>
        <div class="summary-item">{{ __('Expired') }}: {{ $summary['expired'] }}</div>
        @foreach($summary['by_type'] as $type => $count)
            <div class="summary-item">{{ __(ucfirst(str_replace('_', ' ', $type))) }}: {{ $count }}</div>
        @endforeach
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 15%;">{{ __('Employee') }}</th>
                <th style="width: 12%;">{{ __('Department') }}</th>
                <th style="width: 18%;">{{ __('Document Name') }}</th>
                <th style="width: 12%;">{{ __('Type') }}</th>
                <th style="width: 10%;">{{ __('Upload Date') }}</th>
                <th style="width: 10%;">{{ __('Expiry Date') }}</th>
                <th style="width: 10%;">{{ __('Status') }}</th>
                <th style="width: 13%;">{{ __('Tags') }}</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data as $document)
            <tr>
                <td>{{ $document['Employee'] }}</td>
                <td>{{ $document['Department'] }}</td>
                <td>{{ $document['Document Name'] }}</td>
                <td>{{ $document['Type'] }}</td>
                <td>{{ $document['Upload Date'] }}</td>
                <td>{{ $document['Expiry Date'] }}</td>
                <td class="status-{{ strtolower(str_replace(' ', '-', $document['Status'])) }}">
                    {{ $document['Status'] }}
                </td>
                <td>{{ $document['Tags'] }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        {{ __('Document Inventory Report') }} | {{ __('Total Documents') }}: {{ count($data) }} |
        {{ __('Generated by HRMS') }} | {{ __('Page') }} {PAGENO} {{ __('of') }} {nbpg}
    </div>
</body>
</html>