<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ __('Employee Directory Report') }} - {{ now()->format('Y-m-d') }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 10px;
            line-height: 1.4;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #c6a44a;
            padding-bottom: 10px;
        }
        .company-name {
            font-size: 16px;
            font-weight: bold;
            color: #2e4029;
            margin-bottom: 5px;
        }
        .report-title {
            font-size: 14px;
            color: #c6a44a;
            margin-bottom: 5px;
        }
        .report-date {
            font-size: 10px;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #2e4029;
            color: white;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .status-active {
            color: #28a745;
            font-weight: bold;
        }
        .status-inactive {
            color: #ffc107;
            font-weight: bold;
        }
        .status-terminated {
            color: #dc3545;
            font-weight: bold;
        }
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 8px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 5px;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="company-name">{{ __('Sarie Eldin & Partners Legal Advisors') }}</div>
        <div class="report-title">{{ __('Employee Directory Report') }}</div>
        <div class="report-date">{{ __('Generated on') }}: {{ now()->format('F j, Y \a\t g:i A') }}</div>
        @if($filters)
            <div class="report-date">
                @if($filters['department_id'] ?? null)
                    {{ __('Department') }}: {{ \App\Models\Department::find($filters['department_id'])->name_en ?? 'Unknown' }} |
                @endif
                @if($filters['position_id'] ?? null)
                    {{ __('Position') }}: {{ \App\Models\Position::find($filters['position_id'])->name_en ?? 'Unknown' }} |
                @endif
                @if($filters['employment_status'] ?? null)
                    {{ __('Status') }}: {{ ucfirst($filters['employment_status']) }}
                @endif
            </div>
        @endif
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 15%;">{{ __('Employee Code') }}</th>
                <th style="width: 20%;">{{ __('Full Name') }}</th>
                <th style="width: 15%;">{{ __('Department') }}</th>
                <th style="width: 15%;">{{ __('Position') }}</th>
                <th style="width: 10%;">{{ __('Status') }}</th>
                <th style="width: 10%;">{{ __('Hire Date') }}</th>
                <th style="width: 15%;">{{ __('Manager') }}</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data as $employee)
            <tr>
                <td>{{ $employee['Employee Code'] }}</td>
                <td>{{ $employee['Full Name'] }}</td>
                <td>{{ $employee['Department'] }}</td>
                <td>{{ $employee['Position'] }}</td>
                <td class="status-{{ strtolower($employee['Employment Status']) }}">
                    {{ $employee['Employment Status'] }}
                </td>
                <td>{{ $employee['Hire Date'] }}</td>
                <td>{{ $employee['Manager'] }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        {{ __('Employee Directory Report') }} | {{ __('Total Employees') }}: {{ count($data) }} |
        {{ __('Generated by HRMS') }} | {{ __('Page') }} {PAGENO} {{ __('of') }} {nbpg}
    </div>
</body>
</html>